import fs from "node:fs/promises";
import path from "node:path";
import { FILES_TO_COPY, SAFE_STATE_KEYS } from "./constants.js";
import { copyFileEnsured, ensureDir, resetDir, writeJson } from "./fs-utils.js";
import { readStateKeys } from "./sqlite.js";

export async function collect(config) {
  const packageDir = config.package.outputDir;
  const manifest = {
    collectedAtUtc: new Date().toISOString(),
    source: {
      roamingCursorDir: config.source.roamingCursorDir,
      cursorHomeDir: config.source.cursorHomeDir,
      mcpConfigPath: config.source.mcpConfigPath
    },
    files: [],
    stateKeys: SAFE_STATE_KEYS
  };

  await resetDir(packageDir);

  for (const fileDef of FILES_TO_COPY) {
    const sourcePath = path.join(config.source.roamingCursorDir, ...fileDef.relativeSource);
    const packagePath = path.join(packageDir, ...fileDef.relativePackage);

    await copyFileEnsured(sourcePath, packagePath);
    manifest.files.push({
      id: fileDef.id,
      sourcePath,
      packagePath: path.relative(packageDir, packagePath)
    });
  }

  const mcpPackagePath = path.join(packageDir, "files", "cursor-home", "mcp.json");
  await copyFileEnsured(config.source.mcpConfigPath, mcpPackagePath);
  manifest.files.push({
    id: "mcp",
    sourcePath: config.source.mcpConfigPath,
    packagePath: path.relative(packageDir, mcpPackagePath)
  });

  if (config.options.includeWindowState) {
    const stateDbPath = path.join(config.source.roamingCursorDir, "User", "globalStorage", "state.vscdb");
    const stateValues = await readStateKeys(stateDbPath, SAFE_STATE_KEYS);
    await writeJson(path.join(packageDir, "state", "global-state.json"), stateValues);

    const storageJsonSourcePath = path.join(config.source.roamingCursorDir, "User", "globalStorage", "storage.json");
    const storageJsonPackagePath = path.join(packageDir, "state", "storage.json");
    const storageRaw = await fs.readFile(storageJsonSourcePath, "utf8");
    const storageJson = JSON.parse(storageRaw);
    const safeStorageJson = {
      theme: storageJson.theme,
      themeBackground: storageJson.themeBackground,
      windowSplash: storageJson.windowSplash
    };

    await writeJson(storageJsonPackagePath, safeStorageJson);
    manifest.files.push({
      id: "state-export",
      sourcePath: stateDbPath,
      packagePath: "state/global-state.json"
    });
  }

  await ensureDir(path.join(packageDir, "notes"));
  await fs.writeFile(
    path.join(packageDir, "notes", "README.txt"),
    [
      "This package was generated by cursor-transfer-tool.",
      "It contains only minimal Cursor settings, MCP config, and safe layout state."
    ].join("\r\n"),
    "utf8"
  );

  await writeJson(path.join(packageDir, "manifest.json"), manifest);

  return {
    packageDir,
    manifest
  };
}
